#
# Time-stamp: <2008-04-23 17:05:23 hcz>
#
# Run "make install" to install the gemplug components into their
# places
#
install:
	install -m 755 gemplug /usr/local/bin
	install -D -m 644 gemplug.1 /usr/local/share/man/man1
	install -m 644 74-sispmctl.rules /etc/udev/rules.d
